---
variables:
- name: BuildParameters.RestoreBuildProjects
  value: "**/*.csproj"
- name: BuildParameters.TestProjects
  value: "**/*[Tt]ests/*.csproj"
name: "$(date:yyyyMMdd)$(rev:.r)"
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
  - task: NodeTool@0
    displayName: Use Node 10.16.3
    inputs:
      versionSpec: 10.16.3
  - task: Npm@1
    displayName: npm install
    inputs:
      workingDir: TailwindTraders.Website/Source/Tailwind.Traders.Web/ClientApp
      verbose: false
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: "$(BuildParameters.RestoreBuildProjects)"
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: "$(BuildParameters.RestoreBuildProjects)"
      arguments: "--configuration $(BuildConfiguration)"
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: "$(BuildParameters.TestProjects)"
      arguments: "--configuration $(BuildConfiguration)"
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: true
      projects: "$(BuildParameters.RestoreBuildProjects)"
      arguments: "--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)"
      zipAfterPublish: true
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)/appservice'
    inputs:
      SourceFolder: Deploy/appservice
      TargetFolder: "$(build.artifactstagingdirectory)/appservice"
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: "$(build.artifactstagingdirectory)"
      TargetPath: "\\\\my\\share\\$(Build.DefinitionName)\\$(Build.BuildNumber)"
